apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer-deployment
  labels:
    app: metadata-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-writer
  template:
    metadata:
      labels:
        app: metadata-writer
    spec:
      containers:
      - name: main
        image: python:3.7
        command:
        - sh
        - -e
        - -c
        - |
          python3 -m pip install kubernetes 'ml-metadata==0.15.2' --upgrade --quiet --user --no-warn-script-location
          #wget --quiet -O /tmp/metadata_writer.py https://raw.githubusercontent.com/Ark-kun/pipelines/Metadata-Writer-0.2/sdk/metadata_writer/metadata_writer.py
          curl --silent --show-error https://raw.githubusercontent.com/Ark-kun/pipelines/Metadata-Writer-0.2/sdk/metadata_writer/metadata_writer.py >/tmp/metadata_writer.py
          echo "Starting the Metadata writer"
          python3 -u /tmp/metadata_writer.py
