apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer-deployment
  labels:
    app: metadata-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-writer
  template:
    metadata:
      labels:
        app: metadata-writer
    spec:
      containers:
      - name: main
        image: gcr.io/ml-pipeline-test/metadata-writer
